### ISSUE TITLE
Cannot add VSX-933

### ISSUE THREAD

**Issue by iewl** [crowbarz/ha-pioneer_async#47]
I tried reading through all the closed issues, but I can't seem to get my 933 working. I can access the webpage on my browser and I can control the AVR with the Pioneer Remote app, but I can't find the right port it seems. I tried every port I saw in all the closed issues, but none of them work. 8102 and 8103 fail instantly, 23 thinks for 2 seconds and doesn't give an error message. 80 gives this error: 'Unexpected exception: Zone 1 not found on AVR'.

What am I doing wrong? Is there a way to add my AVR?

**Comment by pantherale0** [comment]
23 sounds like it's probably the correct port, but yh exception is due to some compatibility issue. Perhaps different commands are used.

What year is it? If it's too new it probably isn't compatible with this library. In fact, test connection with the iControlAV5 app, if it does not work with that, it won't work with this integration and instead you should use the onkyo integration.

**Comment by iewl** [comment]
You were right! I think the VSX933 is too new. I added it with the Onkyo integration and it works now. Thanks for your quick reply!
