### ISSUE TITLE
Implements device_state_attributes

### ISSUE THREAD

**Issue by Varming73** [crowbarz/ha-pioneer_async#7]
I get these errors:

Entity media_player.vsx_528_2 (<class 'custom_components.pioneer_async.media_player.PioneerZone'>) implements device_state_attributes. Please report it to the custom component author.
Entity media_player.vsx_528_zone_2_2 (<class 'custom_components.pioneer_async.media_player.PioneerZone'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by crowbarz** [comment]
Are the messages you posted errors or warnings? And what HA version are you running?

This has already been fixed in 9b348cd37ffb413b927fede956bc860197c4c7a1 but there hasn't been a release since that commit. I have been waiting to resolve any issues with 2022.3 before releasing, but cannot upgrade to that version yet due to an integration issue that affects my setup.

**Comment by crowbarz** [comment]
This should be fixed in 0.6.2.
